{% set name = "eo-learn-core" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0cba92e779e852ddccc0cd7e6ba15581e368b8db2d97b9d23c93f1c0ce2e20a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - attrs >=18.2.0
    - geopandas
    - numpy >=1.16
    - python >=3.5
    - python-dateutil
    - sentinelhub >=2.5.0
    - tqdm >=4.27
    - fs
    - fs-s3fs
test:
  imports:
    - eolearn
    - eolearn.core

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Core Machine Learning Framework at Sinergise
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.core.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - zigaluksic
    - mxr-conda
