{% set name = "eo-learn-core" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2d3438160abd693af816575d701bcba06587300d0d9d8d2b2cb97aec3c17aa9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - attrs >=18.2.0
    - geopandas
    - numpy >=1.16
    - python >=3.5
    - python-dateutil
    - sentinelhub >=2.5.0
    - tqdm >=4.27
    - fs
    - fs-s3fs
test:
  imports:
    - eolearn
    - eolearn.core

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Core Machine Learning Framework at Sinergise
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.core.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mwilson8
    - dcunn
    - oblute
    - rluria14
    - benhuff
